### ISSUE TITLE
Project does not compile without errors

### ISSUE THREAD

**Issue by sdemius** [unusual-thoughts/8x8matrix#1]
Seems commited Tlc5947.cpp is old version and not correspond to Tlc5947.h

I have many errors, first error for example:
error: conflicting declaration 'uint8_t tlc_GSData [24]

In the file: Tlc5947.cpp
 uint8_t tlc_GSData[NUM_TLCS * 24];
In the file: Tlc5947.h
 extern uint8_t tlc_GSData[8 * 36];

**Comment by unusual-thoughts** [comment]
Should be fixed now. Library is still based on an old version of Tlc5940 though

**Comment by sdemius** [comment]
Ok, thank you!

**Comment by unusual-thoughts** [comment]
Just wondering, what are you using this for? do you have the same RGB matrix ? are you planning to etch the pcb?

**Comment by sdemius** [comment]
Yes, I have same matrix. Now I just test this matrix. Maybe later I will make a screen with this matrices.
